<?php

namespace CHATONDL13Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * chatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chatRepository extends EntityRepository
{
}
